### PR TITLE
Making package pip installable

### PR DESCRIPTION
**Pull request by mjstevens777**
This new version of the package should be installable via pip. I tested with python 3 on OS X and a fresh install of ubuntu.

- I reworked the setup.py script to require numpy and cython.
- I added a package name so that it installs under `pygco` instead of `UNKNOWN`
- I put the `gco_src` files (without MATLAB) into the repo permanently so that the separate Makefile step is not necessary.

### CODE REVIEW

**Comment by amueller** [comment]
The gco license prohibits redistribution, see the ``GCO_README.TXT`` that you included.

**Comment by mjstevens777** [comment]
Thanks for the fast review. I saw the section on citations, but I missed the part about distribution, thanks for catching that. I updated the process to automatically pull the sources instead of baking them in. I admit, my approach is pretty hacky so feel free to reject it.

**Comment by amueller** [comment]
I mean my original approach was pretty hacky and of questionable legality ;)

**Comment by amueller** [comment]
That actually doesn't look to bad. If you want brownie points, the right thing to do would be to have this tested on travis - and this repo should have travis anyhow.

This thing is very low on my list of priorities, tbh, so if you don't feel like working on CI, I'm happy to merge without it.

Have you looked at OpenGM? They have a very comprehensive suite of wrappers and implementations.

**Comment by amueller** [comment]
my change was insubstantial, but I needed to enable travis on the repo for it to run, and then needed to make a commit so it actually runs.

**Comment by mjstevens777** [comment]
Sounds good. Thanks for your help on this! Go ahead and merge

OpenGM and pystruct are great, I just have trouble installing them on OS X. They also don't seem to support label costs. I am planning on raising a 10-line change for that as well, would you like that here or in a separate PR?

**Pull request merged**
